### PR TITLE
Fix bug in hosting bundle registry query

### LINKED ISSUE #140: The hosting bundles aren't listed
As you can see , the hosting bundles are installed, but not listed when using the uninstall tool.

image

### PR DESCRIPTION
**Pull request by sfoslund**
Fixes #140

### CODE REVIEW

**Comment by sfoslund** [comment]
Weird, azdo is reporting success but GitHub hangs here even on rerun.

**Comment by sfoslund** [comment]
Reopening to try to fix azdo issue

**Comment by sfoslund** [comment]
@wli3 the checks are passing behind the scenes but GitHub isn't reporting success, do you know how to fix this or would it be okay to merge anyway?

**Comment by wli3** [comment]
@sfoslund try to pull the change, run `git commit --amend`. This will give the last commit a new commit hash and the `git push --force` to the branch. The should reset the build on the CI.

We have been burned before by merging "should be good" PR directly.

**Pull request merged**
